name: rafiq_gp
description: "Rafiq - AI-powered child health companion app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^2.1.0


  # ðŸŽ¨ ÙˆØ§Ø¬Ù‡Ø§Øª ÙˆØ£ÙŠÙ‚ÙˆÙ†Ø§Øª
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # ðŸ“¸ Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„ÙƒØ§Ù…ÙŠØ±Ø§ ÙˆØ§Ù„ØµÙˆØ±
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.11
  video_player: ^2.9.1

  # ðŸ”¥ Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.4

  # ðŸ§  ØªØ´ØºÙŠÙ„ Ù†Ù…ÙˆØ°Ø¬ ONNX
  onnxruntime: ^1.4.1

  # ðŸ§© ØªØ­Ù„ÙŠÙ„ Ø§Ù„ØµÙˆØ±
  image: ^4.5.4

  # ðŸ’¾ ØªØ®Ø²ÙŠÙ† Ù…Ø­Ù„ÙŠ
  shared_preferences: ^2.3.2
  flutter_cache_manager: ^3.4.1

  # ðŸ”¤ ØªØµØºÙŠØ± Ø­Ø¬Ù… Ø§Ù„Ø®Ø· ØªÙ„Ù‚Ø§Ø¦ÙŠ Ù„Ø§Ø³Ù… Ø§Ù„Ø·ÙÙ„
  auto_size_text: ^3.0.0   # â† Ù‡Ù†Ø§ Ø§Ù„Ø¥Ø¶Ø§ÙØ© Ø§Ù„Ù…Ù‡Ù…Ø©

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/icons/
    - lib/models_RafiqSkinModel_idx.onnx
    - lib/labels.txt

